
background {
    monitor =
    path =
    blur_size = 5
    blur_passes = 4
    noise = 0.01
    contrast = 1.2
    brightness = 0.7
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}
input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.8
    dots_center = true
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    inner_color = rgba(0, 0, 0, 0.3)
    outer_color = rgba(255, 255, 255, 0.15)
    font_color = rgb(225, 226, 233)
    check_color = rgba(163, 201, 255, 0.5)
    fail_color = rgba(243, 139, 168, 0.5)
    capslock_color = rgba(249, 226, 175, 0.5)
    rounding = 16
    position = 0, 50
    halign = center
    valign = bottom
}

#Top text
label {
    monitor =
    text = ぼっち・
    font_size = 12
    font_family = JetBrains Mono Nerd Font 10
    position = -38, -45
    halign = center
    valign = top
}
label {
    monitor =
    text = ざ
    font_size = 12
    font_family = JetBrains Mono Nerd Font 10
    position = 3, -45
    halign = center
    valign = top
}
label {
    monitor =
    text = ・ろっく！
    font_size = 12
    font_family = JetBrains Mono Nerd Font 10
    position = 53, -50
    halign = center
    valign = top
}

# Current time
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>"
    font_size = 64
    font_family = JetBrains Mono Nerd Font 10
    position = 0, 46
    halign = center
    valign = center
}

# User label
label {
    monitor =
    text = h1 4g41n, <span size="larger">$USER</span>
    font_size = 20
    font_family = JetBrains Mono Nerd Font 10
    position = 0, -15
    halign = center
    valign = center
}


