###############################
### Special Workspace Binds ###
###############################

# Original scratchpad
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Music / media scratchpad
bind = $mainMod, M, togglespecialworkspace, music
bind = $mainMod SHIFT, M, movetoworkspace, special:music

# Messenger / chat scratchpad
bind = $mainMod, D, togglespecialworkspace, chat
bind = $mainMod SHIFT, D, movetoworkspace, special:chat
