###############################
### Special Workspace Binds ###
###############################

# Original scratchpad
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Terminal scratchpad
bind = $mainMod, T, togglespecialworkspace, term
bind = $mainMod SHIFT, T, movetoworkspace, special:term

# Music / media scratchpad
bind = $mainMod, M, togglespecialworkspace, music
bind = $mainMod SHIFT, M, movetoworkspace, special:music

# Messenger / chat scratchpad
bind = $mainMod, I, togglespecialworkspace, chat
bind = $mainMod SHIFT, I, movetoworkspace, special:chat

# File manager scratchpad
bind = $mainMod, N, togglespecialworkspace, files
bind = $mainMod SHIFT, N, movetoworkspace, special:files
