[general]
framerate = 60
bars = 32

[smoothing]
integral = 0
monstercat = 0
gravity = 1000
ignore_fifo_delay = 1

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
bar_delimiter = 59
